# Generated by Django 5.1.1 on 2024-09-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
        migrations.AddField(
            model_name='notice',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='notices/pdfs/'),
        ),
    ]
